name: WeatherForecastApiApplication
trigger:
- master

variables:
  buildConfiguration: "Release"
  dotNetVersion: '6.0.x'
  resourceGroupName: 'rg-weather-forecast'
  location: 'westeurope'
  azureSubscription: 'azure-service-connection'  
  dotNetFramework: 'net6.0'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build
  jobs:

  - job: BuildApiApplication
    displayName: Build the API application
    steps:

    - task: UseDotNet@2
      displayName: Install .NET Framework version
      inputs:
        packageType: 'sdk'
        version: $(dotNetVersion)
        includePreviewVersions: true
        installationPath: $(Agent.ToolsDirectory)/dotnet  

    - task: DotNetCoreCLI@2
      displayName: Build API application
      inputs:
        command: 'build'
        projects: '**/WeatherForecastApi.csproj'
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration $(buildConfiguration) 

    - task: DotNetCoreCLI@2
      displayName: Create API application artifact
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True    

    - task: PublishBuildArtifacts@1
      displayName: Publish API application artifact
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)"
        ArtifactName: "api"
        publishLocation: Container   

- stage: Deploy
  displayName: Deployment
  jobs:
            
  - job: DeployApiApplication
    dependsOn: DeployInfrastructure
    displayName: Deploy API application
    steps:

    - task: DownloadBuildArtifacts@0
      displayName: Download API application artifact
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'api'
        downloadPath: '$(System.ArtifactsDirectory)'    

    - task: AzureWebApp@1
      displayName: Deploy API application
      inputs:
        appType: webApp
        azureSubscription: $(azureSubscription)
        appName: 'app-weatherforecastapi'
        package: "$(System.ArtifactsDirectory)/api/*.zip"

 